### ISSUE TITLE
TypeError: TMDB is not a constructor

### ISSUE THREAD

**Issue by bobbymannino** [blakejoy/tmdb-ts#16] opened 2023-04-07 18:38 UTC
Not sure what this is. Works in dev fine but building (locally or with vercel) shows this error, any advice?

**Comment by blakejoy** [comment] 2023-04-10 00:01
What version of node and TS are you using?

**Comment by blakejoy** [comment] 2023-04-12 11:10
Will take a look at this today.

**Comment by blakejoy** [comment] 2023-04-13 03:45
Are you using it client side or server side?

**Comment by sayem314** [comment] 2023-04-13 06:48
> Are you using it client side or server side?

Server side on [lunarr-server](https://github.com/lunarr-app/lunarr-server)

**Comment by blakejoy** [comment] 2023-04-13 10:57
> > Are you using it client side or server side?
> 
> Server side on [lunarr-server](https://github.com/lunarr-app/lunarr-server)

Can you try to pull latest and see if the changes made fix this issue? I wasn’t able to reproduce on my side.

**Comment by blakejoy** [comment] 2023-04-13 13:17
Okay. I’ll pull your code down and take a look

**Comment by blakejoy** [comment] 2023-04-14 02:36
Can you try setting `esModuleInterop: true` in your tsconfig?

**Comment by blakejoy** [comment] 2023-04-14 06:57
Still looking at this… I think it has to do with how the tsconfig is set up and the effect it has when it’s transpiling the code. I need to cross reference a project I’m working on but that’s the only thing I can think of.

**Comment by blakejoy** [comment] 2023-04-16 17:25
> Still looking at this… I think it has to do with how the tsconfig is set up and the effect it has when it’s transpiling the code. I need to cross reference a project I’m working on but that’s the only thing I can think of.

Ruling it as something with the tsconfig that doesn't coincide with how this is being exported.

**Comment by blakejoy** [comment] 2023-04-16 19:27
> > Still looking at this… I think it has to do with how the tsconfig is set up and the effect it has when it’s transpiling the code. I need to cross reference a project I’m working on but that’s the only thing I can think of.
> 
> Ruling it as something with the tsconfig in your project that doesn't coincide with how this is being exported.

Looks like after doing some local testing... it has to do with the default export of TMDB from the barrel file.

**Comment by blakejoy** [comment] 2023-04-26 02:53
This was fixed in v1.0

**Closed by blakejoy** 2023-04-26 02:53 UTC

**Comment by sayem314** [comment] 2023-04-30 08:56
Fix confirmed. Thanks!
